{   "bin_fn"                    : "build/GluonicLQCD",
    "runName"                   : "configP128run",
    "N"                         : 24,
    "NT"                        : 48,
    "subDims"                   : [6, 6, 12, 12],
    "beta"                      : 6.0,
    "NCf"                       : 1,
    "NCor"                      : 2000,
    "NTherm"                    : 0,
    "NFlows"                    : 0,
    "NUpdates"                  : 10,
    "storeCfgs"                 : 0,
    "storeThermCfgs"            : 0,
    "verboseRun"                : 1,
    "hotStart"                  : 0,
    "expFunc"                   : "morningstar", # options: luscher, taylor2, taylor4
    "observables"               : ["plaq"], # Optional: topologicalCharge, energyDensity
    "flowObservables"           : ["plaq"], # Optional: topologicalCharge, energyDensity
    "uTest"                     : 0,
    "uTestVerbose"              : 0,
    "SU3Eps"                    : 0.24,
    "flowEpsilon"               : 0.01,
    "metropolisSeed"            : 0,
    "randomMatrixSeed"          : 0,
    "threads"                   : 128,
    "cpu_approx_runtime_hr"     : 1,
    "cpu_approx_runtime_min"    : 30,
    "cpu_memory"                : 3800,
    "account_name"              : "nn2977k"}