{   "bin_fn"        : "%s/build/GluonicLQCD" % os.getcwd(),
    "runName"       : "configP128run",
    "beta"          : 6.0,
    "N"             : 24,
    "NT"            : 48,
    "NTherm"        : 100,
    "NCor"          : 20,
    "NCf"           : 100,
    "NUpdates"      : 10,
    "SU3Eps"        : 0.24,
    "threads"       : 128,
    "storeCfgs"     : 1,
    "storeThermCfgs": 0,
    "hotStart"      : 0,
    "subDims"       : [6, 6, 12, 12],
    "cpu_approx_runtime": 2,
    "cpu_memory"    : 3800,
    "account_name"  : "nn2977k"}