{   "bin_fn"        : "%s/build/GluonicLQCD" % os.getcwd(),
    "runName"       : "configP64run",
    "beta"          : 6.0,
    "N"             : 24,
    "NT"            : 48,
    "NTherm"        : 0,
    "NCor"          : 2000,
    "NCf"           : 1,
    "NUpdates"      : 10,
    "SU3Eps"        : 0.24,
    "threads"       : 64,
    "storeCfgs"     : 0,
    "storeThermCfgs": 0,
    "hotStart"      : 0,
    "subDims"       : [12, 12, 12, 6], # RUN WITH REVERSED LIST AS WELL!
    "cpu_approx_runtime": 2,
    "cpu_memory"    : 3800,
    "account_name"  : "nn2977k"}