{   "bin_fn"        : "build/GluonicLQCD",
    "runName"       : "configP32run",
    "beta"          : 6.0,
    "N"             : 24,
    "NT"            : 48,
    "NTherm"        : 0,
    "NCor"          : 2000,
    "NCf"           : 1,
    "NFlows"        : 0,
    "NUpdates"      : 10,
    "SU3Eps"        : 0.24,
    "threads"       : 32,
    "storeCfgs"     : 0,
    "storeThermCfgs": 0,
    "hotStart"      : 0,
    "subDims"       : [12, 12, 12, 12],
    "uTest"         : 0,
    "uTestVerbose"  : 0,
    "cpu_approx_runtime_min" : 0,
    "cpu_approx_runtime_hr" : 2,
    "cpu_memory"    : 3800,
    "account_name"  : "nn2977k"}