{   "bin_fn"                    : "build/GluonicLQCD",
    "runName"                   : "prodRunBeta6_2",
    "N"                         : 32,
    "NT"                        : 64,
    "subDims"                   : [8, 8, 8, 8],
    "beta"                      : 6.2,
    "NCf"                       : 500,
    "NCor"                      : 200,
    "NTherm"                    : 1000,
    "NFlows"                    : 1000,
    "NUpdates"                  : 10,
    "storeCfgs"                 : 0,
    "storeThermCfgs"            : 0,
    "verboseRun"                : 1,
    "hotStart"                  : 0,
    "expFunc"                   : "morningstar", # options: luscher, taylor2, taylor4
    "observables"               : ["plaquette","topc","energy"], # Optional: topologicalCharge, energyDensity
    "flowObservables"           : ["plaquette","topc","energy"], # Optional: topologicalCharge, energyDensity
    "uTest"                     : 0,
    "uTestVerbose"              : 0,
    "SU3Eps"                    : 0.24,
    "flowEpsilon"               : 0.01,
    "metropolisSeed"            : 0,
    "randomMatrixSeed"          : 0,
    "threads"                   : 512,
    "cpu_approx_runtime_hr"     : 30,
    "cpu_approx_runtime_min"    : 0,
    "cpu_memory"                : 3800,
    "account_name"              : "nn2977k"}