{   "bin_fn"        : "%s/build/GluonicLQCD" % os.getcwd(),
    "runName"       : "prodRun1",
    "beta"          : 6.0,
    "N"             : 24,
    "NT"            : 48,
    "NTherm"        : 1000,
    "NCor"          : 200,
    "NCf"           : 1000,
    "NFlows"        : 1000,
    "NUpdates"      : 10,
    "SU3Eps"        : 0.24,
    "threads"       : 512,
    "storeCfgs"     : 0,
    "storeThermCfgs": 0,
    "hotStart"      : 0,
    "subDims"       : [6,6,6,6],
    "uTest"         : 0,
    "uTestVerbose"  : 0,
    "cpu_approx_runtime_min" : 0,
    "cpu_approx_runtime_hr" : 13,
    "cpu_memory"    : 3800,
    "account_name"  : "nn2977k"}