{   "bin_fn"        : "build/GluonicLQCD",
    "runName"       : "job1",
    "beta"          : 6.1,
    "N"             : 48,
    "NT"            : 96,
    "NTherm"        : 1000,
    "NCor"          : 800,
    "NCf"           : 250,
    "NFlows"        : 1000,
    "NUpdates"      : 10,
    "SU3Eps"        : 0.24,
    "threads"       : 512,
    "storeCfgs"     : 0,
    "storeThermCfgs": 0,
    "hotStart"      : 0,
    "subDims"       : [12,12,12,6],
    "uTest"         : 0,
    "uTestVerbose"  : 0,
    "cpu_approx_runtime_min" : 0,
    "cpu_approx_runtime_hr" : 150,
    "cpu_memory"    : 3800,
    "account_name"  : "nn2977k"}