{   "bin_fn"        : "%s/build/GluonicLQCD" % os.getcwd(),
    "runName"       : "job1",
    "beta"          : 6.1,
    "N"             : 28,
    "NT"            : 56,
    "NTherm"        : 1000,
    "NCor"          : 200,
    "NCf"           : 500,
    "NUpdates"      : 10,
    "SU3Eps"        : 0.24,
    "threads"       : 512,
    "storeCfgs"     : 1,
    "storeThermCfgs": 0,
    "hotStart"      : 0,
    "subDims"       : [7,7,7,7],
    "cpu_approx_runtime": 2,
    "cpu_memory"    : 3800,
    "account_name"  : "nn2977k"}