{   "bin_fn"        : "build/GluonicLQCD",
    "runName"       : "test_run_new_counting",
    "beta"          : 6.0,
    "N"             : 16,
    "NT"            : 32,
    "NTherm"        : 200,
    "NCor"          : 20,
    "NCf"           : 10,
    "NFlows"        : 10,
    "NUpdates"      : 10,
    "SU3Eps"        : 0.24,
    "threads"       : 16,
    "storeCfgs"     : True,
    "storeThermCfgs": False,
    "hotStart"      : False,
    "subDims"       : [],
    "uTest"         : False,
    "uTestVerbose"  : False,
    "cpu_approx_runtime": 2,
    "cpu_memory"    : 3800,
    "account_name"  : "nn2977k"}