{   "bin_fn"        : "build/GluonicLQCD",
    "runName"       : "job1",
    "beta"          : 6.0,
    "N"             : 16,
    "NT"            : 16,
    "NTherm"        : 200,
    "NCor"          : 20,
    "NCf"           : 100,
    "NFlows"        : 0,
    "NUpdates"      : 10,
    "SU3Eps"        : 0.24,
    "threads"       : 64,
    "storeCfgs"     : True,
    "storeThermCfgs": False,
    "hotStart"      : False,
    "subDims"       : [],
    "uTest"         : False,
    "uTestVerbose"  : False,
    "cpu_approx_runtime": 2,
    "cpu_memory"    : 3800,
    "account_name"  : "nn2977k"}