{   "bin_fn"                    : "build/GluonicLQCD",
    "runName"                   : "sizeScaling16cube32",
    "N"                         : 32,
    "NT"                        : 16,
    "subDims"                   : [4, 8, 8, 8],
    "beta"                      : 6.0,
    "NCf"                       : 1,
    "NCor"                      : 2000,
    "NTherm"                    : 0,
    "NFlows"                    : 0,
    "NUpdates"                  : 10,
    "storeCfgs"                 : False,
    "storeThermCfgs"            : False,
    "verboseRun"                : False,
    "hotStart"                  : False,
    "expFunc"                   : "morningstar", # options: luscher, taylor2, taylor4
    "observables"               : ["plaq"], # Optional: topologicalCharge, energyDensity
    "flowObservables"           : ["plaq"], # Optional: topologicalCharge, energyDensity
    "uTest"                     : False,
    "uTestVerbose"              : False,
    "SU3Eps"                    : 0.24,
    "flowEpsilon"               : 0.01,
    "metropolisSeed"            : 0,
    "randomMatrixSeed"          : 0,
    "threads"                   : 256,
    "cpu_approx_runtime_hr"     : 1,
    "cpu_approx_runtime_min"    : 0,
    "cpu_memory"                : 3800,
    "account_name"              : "nn2977k"}