{   "bin_fn"        : "%s/build/GluonicLQCD" % os.getcwd(),
    "runName"       : "sizeScaling28cube56",
    "beta"          : 6.0,
    "N"             : 28,
    "NT"            : 56,
    "NTherm"        : 0,
    "NCor"          : 2000,
    "NCf"           : 1,
    "NUpdates"      : 10,
    "SU3Eps"        : 0.24,
    "threads"       : 64,
    "storeCfgs"     : 0,
    "storeThermCfgs": 0,
    "hotStart"      : 0,
    "subDims"       : [14,14,14,7],
    "cpu_approx_runtime": 3,
    "cpu_memory"    : 3800,
    "account_name"  : "nn2977k"}