{   "bin_fn"        : "%s/build/GluonicLQCD" % os.getcwd(),
    "runName"       : "sizeScaling16cube32",
    "beta"          : 6.0,
    "N"             : 16,
    "NT"            : 32,
    "NTherm"        : 100,
    "NCor"          : 20,
    "NCf"           : 10,
    "NUpdates"      : 10,
    "SU3Eps"        : 0.24,
    "threads"       : 64,
    "storeCfgs"     : 1,
    "storeThermCfgs": 0,
    "hotStart"      : 0,
    "subDims"       : [8,8,8,8],
    "cpu_approx_runtime": 1,
    "cpu_memory"    : 3800,
    "account_name"  : "nn2977k"}