import numpy as np

"""
Program for checking if the files that are written have the same structure.
Takes an file generated by N processors, and loads another one that has loaded,
and then written the same configuration to file.
"""

file1 = np.fromfile("output/scalar16cubed16run1.bin")
file2 = np.fromfile("output/configs_profiling_run_beta6.000000_config1.bin")

errors = 0

for elem1,elem2 in zip(file1,file2):
	if elem1 != elem2:
		errors += 1

if errors == 0:
	print "SUCCESS: %d discrepancies found" % errors
else:
	print "FAILURE: %d discrepancies found" % errors